# GAT Node Classification Configuration
# Based on: Veličković, P., Casanova, A., Liò, P., Cucurull, G., Romero, A., & Bengio, Y. (2018). Graph attention networks.

out_dir: results
cfg: gat
cfg_file: configs/pyg/gat_node.yaml
repeat: 1
mark_done: false
opts: []

# Dataset
dataset:
  format: PyG
  name: Cora  # Can be: Cora, CiteSeer, PubMed, Reddit, Yelp, Elliptic
  task: node
  task_type: classification
  transductive: true
  split: [0.8, 0.1, 0.1]

# Model
model:
  type: gat
  loss_fun: cross_entropy

# GNN Architecture
gnn:
  layer_type: gat
  num_layers: 2
  hidden_dim: 64
  dropout: 0.6
  heads: 8
  concat: true
  negative_slope: 0.2
  agg: add
  bias: true
  l2norm: false

# Training
train:
  auto_resume: true
  epoch_resume: 0
  ckpt_iter: -1
  ckpt_clean: true

# Optimization
optim:
  optimizer: adam
  base_lr: 0.005
  max_epoch: 200
  weight_decay: 5e-4
  scheduler: reduce_on_plateau
  patience: 10
  lr_decay: 0.5

# System
device: cuda
seed: 42
mem:
  inplace: false 