# GCN Node Classification Configuration with Elliptic Dataset
# Based on: Kipf, T. N., & Welling, M. (2017). Semi-supervised classification with graph convolutional networks.

out_dir: results

# Dataset
dataset:
  format: PyG
  name: Elliptic
  task: node
  task_type: classification_binary
  transductive: false
  transform: none

# Training
train:
  batch_size: 10
  eval_period: 20
  ckpt_period: 100

# Model
model:
  type: gcn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add

# GNN Architecture
gnn:
  layers_pre_mp: 1
  layers_mp: 2
  layers_post_mp: 1
  dim_inner: 64
  layer_type: gcn
  stage_type: stack
  batchnorm: true
  act: prelu
  dropout: 0.5
  agg: add
  normalize_adj: false

# Optimization
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 200
  weight_decay: 5e-4 