# GraphSAGE Node Classification Configuration
# Based on: Hamilton, W. L., Ying, R., & Leskovec, J. (2017). Inductive representation learning on large graphs.

out_dir: results
cfg: graphsage
cfg_file: configs/pyg/graphsage_node.yaml
repeat: 1
mark_done: false
opts: []

# Dataset
dataset:
  format: PyG
  name: Reddit  # Good for inductive learning: Reddit, Yelp, Elliptic
  task: node
  task_type: classification
  transductive: false
  split: [0.8, 0.1, 0.1]

# Model
model:
  type: graphsage
  loss_fun: cross_entropy

# GNN Architecture
gnn:
  layer_type: graphsage
  num_layers: 2
  hidden_dim: 64
  dropout: 0.5
  aggregator: mean  # Options: mean, max, lstm
  agg: add
  bias: true
  l2norm: false

# Training
train:
  auto_resume: true
  epoch_resume: 0
  ckpt_iter: -1
  ckpt_clean: true

# Optimization
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 200
  weight_decay: 5e-4
  scheduler: reduce_on_plateau
  patience: 10
  lr_decay: 0.5

# System
device: cuda
seed: 42
mem:
  inplace: false 